parameters:
  mailer.gmail_user: 'sebastien@gmail.com'
  mailer.gmail_password: 'password'
  firstname: "Lior"

services:
#  done in index.html
#  with $container->registerForAutoconfiguration(HasLoggerInterface::class)->addTag('with_logger');
#   + set autoconfigure: true on services to be accepted. We pass 'with_logger'
  _instanceof:
    App\HasLoggerInterface:
      tags: ['with_logger']

  _defaults:
    autowire: true
    autoconfigure: true
    bind:
#      $firstname: "Lior"
      $firstname: "%firstname%"

# loads all files as services
  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection}'

  App\Controller\TestController:
    public: true

  App\Controller\OrderController:
    public: true
    calls:
      - method: sayHello
        arguments: ["Sébastien", 26]

  App\Mailer\MailerInterface:
    alias: App\Mailer\GmailMailer

  App\Texter\TexterInterface:
    alias: App\Texter\SmsTexter

  App\Mailer\GmailMailer:
    arguments:
      - '%mailer.gmail_user%'
      - '%mailer.gmail_password%'

  App\Texter\SmsTexter:
    arguments:
      - "service.sms.com"
      - "apikey123"

#  order_controller: "@App\Controller\OrderController"
  order_controller:
    alias: 'App\Controller\OrderController'
    public: true

