parameters:
  mailer.gmail_user: 'sebastien@gmail.com'
  mailer.gmail_password: 'password'
  firstname: "Lior"

services:
#  done in index.html
#  with $container->registerForAutoconfiguration(HasLoggerInterface::class)->addTag('with_logger');
#   + set autoconfigure: true on services to be accepted. We pass 'with_logger'
  _instanceof:
    App\HasLoggerInterface:
      tags: ['with_logger']

  _defaults:
    autowire: true
    autoconfigure: true
    bind:
#      $firstname: "Lior"
      $firstname: "%firstname%"

  order_controller:
    class: App\Controller\OrderController
    public: true
    calls:
      - method: sayHello
        arguments: ["Bonjour à tous" , 33]
      - method: setSecondaryMailer
        arguments: ["@mailer.gmail"]
#    arguments:
#      $firstname : 'Sebastien'

# for the example, I want to keep this service here to show _instanceof does cross multiple yamls files
  texter.sms:
    autoconfigure: true
    class: App\Texter\SmsTexter
    arguments: [ "service.sms.com", "apikey123" ]
#    arguments: [ "service.sms.com", "apikey123" , "Sebastien"]

#    Alias
  App\Controller\OrderController:
    alias: 'order_controller'
    public: true
  App\Database\Database: '@database'
  App\Mailer\GmailMailer: '@mailer.gmail'
  App\Mailer\SmtpMailer: '@mailer.smtp'
  App\Mailer\MailerInterface: '@mailer.gmail'
  App\Texter\SmsTexter: '@texter.sms'
  App\Texter\FaxTexter: '@texter.fax'
  App\Texter\TexterInterface: '@texter.sms'
  \App\Logger: '@logger'
